/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemoriesIndexRouteImport } from './routes/memories.index'
import { Route as MemoriesIdRouteImport } from './routes/memories.$id'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIdRoute = MemoriesIdRouteImport.update({
  id: '/memories/$id',
  path: '/memories/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/memories/$id': typeof MemoriesIdRoute
  '/memories/': typeof MemoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/memories/$id': typeof MemoriesIdRoute
  '/memories': typeof MemoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/memories/$id': typeof MemoriesIdRoute
  '/memories/': typeof MemoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/search'
    | '/settings'
    | '/timeline'
    | '/memories/$id'
    | '/memories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graph'
    | '/search'
    | '/settings'
    | '/timeline'
    | '/memories/$id'
    | '/memories'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/search'
    | '/settings'
    | '/timeline'
    | '/memories/$id'
    | '/memories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  MemoriesIdRoute: typeof MemoriesIdRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/': {
      id: '/memories/'
      path: '/memories'
      fullPath: '/memories/'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/$id': {
      id: '/memories/$id'
      path: '/memories/$id'
      fullPath: '/memories/$id'
      preLoaderRoute: typeof MemoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  MemoriesIdRoute: MemoriesIdRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
